BEGIN;

set sql_mode="ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION";

CREATE TABLE IF NOT EXISTS `locker` (
    `id` BIGINT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'id',
    `name` VARCHAR(64) NOT NULL DEFAULT "" COMMENT 'name',
    `version`  BIGINT(11) NOT NULL DEFAULT 0 COMMENT 'version',
    `master` VARCHAR(64) NOT NULL DEFAULT "" COMMENT 'master',
    `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后一次修改时间',
    UNIQUE KEY `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

COMMIT;
